/*
 * generated by Xtext 2.25.0
 */
package gama.core.lang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GamlRuntimeModule extends AbstractGamlRuntimeModule {
}
