/*
 * generated by Xtext 2.25.0
 */
package gama.core.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GamlStandaloneSetup extends GamlStandaloneSetupGenerated {

	public static void doSetup() {
		new GamlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
